--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20.05.2020 18:28:00
-- Server version: 5.5.5-10.3.13-MariaDB-log
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE hospital;

--
-- Drop table `pacient`
--
DROP TABLE IF EXISTS pacient;

--
-- Drop table `vipiska`
--
DROP TABLE IF EXISTS vipiska;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop table `pol`
--
DROP TABLE IF EXISTS pol;

--
-- Drop table `postyplenie`
--
DROP TABLE IF EXISTS postyplenie;

--
-- Set default database
--
USE hospital;

--
-- Create table `postyplenie`
--
CREATE TABLE postyplenie (
  pos_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (pos_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `pol`
--
CREATE TABLE pol (
  pol_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (pol_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `user`
--
CREATE TABLE user (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(55) DEFAULT NULL,
  lastname VARCHAR(55) DEFAULT NULL,
  patronymic VARCHAR(55) DEFAULT NULL,
  pol_id INT(11) DEFAULT NULL,
  vozrast INT(11) DEFAULT NULL,
  pos_id INT(11) DEFAULT NULL,
  data_p DATE DEFAULT NULL,
  opisanie VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE user 
  ADD CONSTRAINT FK_user_pol_pol_id FOREIGN KEY (pol_id)
    REFERENCES pol(pol_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE user 
  ADD CONSTRAINT FK_user_postyplenie_pos_id FOREIGN KEY (pos_id)
    REFERENCES postyplenie(pos_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `vipiska`
--
CREATE TABLE vipiska (
  vipiska_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (vipiska_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `pacient`
--
CREATE TABLE pacient (
  pac_id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) DEFAULT NULL,
  num_palata INT(11) DEFAULT NULL,
  diagnoz VARCHAR(255) DEFAULT NULL,
  vipiska_data DATE DEFAULT NULL,
  vipiska_id INT(11) DEFAULT NULL,
  PRIMARY KEY (pac_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE pacient 
  ADD CONSTRAINT FK_pacient_user_user_id FOREIGN KEY (user_id)
    REFERENCES user(user_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE pacient 
  ADD CONSTRAINT FK_pacient_vipiska_vipiska_id FOREIGN KEY (vipiska_id)
    REFERENCES vipiska(vipiska_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table postyplenie
--
INSERT INTO postyplenie VALUES
(1, 'Направление поликлиники'),
(2, 'Доставлен скорой помощью');

-- 
-- Dumping data for table pol
--
INSERT INTO pol VALUES
(1, 'man'),
(2, 'girl');

-- 
-- Dumping data for table vipiska
--
INSERT INTO vipiska VALUES
(1, 'Выздоровел'),
(2, 'Перевод'),
(3, 'Отправка в санаторий');

-- 
-- Dumping data for table user
--
-- Table hospital.user does not contain any data (it is empty)

-- 
-- Dumping data for table pacient
--
-- Table hospital.pacient does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;